### ISSUE TITLE
.gitignore n'ignore pas le fichier gestionPersonnel.srz

### ISSUE THREAD

**Issue by T-Shai** [alexandreMesle/personnel#1]
Bonjour,   

votre .gitignore ignore le **DOSSIER** "gestionPersonnel.srz" et non pas le **FICHIER** du même nom. 
***
Il faut changer :
```/gestionPersonnel.srz```
En 
```gestionPersonnel.srz```   
***
Cordialement.

**Comment by alexandreMesle** [comment]
Merci beaucoup pour votre remarque. Vous voulez faire un pull request ?

**Comment by T-Shai** [comment]
Non, je ne pense pas, la correction est plutôt mineure. Merci de l'avoir pris en compte !
